// import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      </Head>
      <body>{children}
      </body>

    </html>
  );
}
